jobs:
  include:
    - install:
        - pip install -r requirements-dev.txt
        - pip install -r requirements.txt
        - pip install -U tox-travis
      script: python -m unittest discover gcgc.tests
      language: python
      python:
        - "3.6"
