version: '3'

services:
  gcgc:
    build:
      context: .
    image: tshauck/gcgc
  yeyo:
    image: docker.io/thauck/yeyo:0.3.0-dev.2
    volumes:
      - $PWD:/project
      - $HOME/.gitconfig:/etc/gitconfig
